// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vessel/vessel.proto

package vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Space                int32    `protobuf:"varint,2,opt,name=space,proto3" json:"space,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetSpace() int32 {
	if m != nil {
		return m.Space
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Requirement struct {
	Space                int32    `protobuf:"varint,1,opt,name=space,proto3" json:"space,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requirement) Reset()         { *m = Requirement{} }
func (m *Requirement) String() string { return proto.CompactTextString(m) }
func (*Requirement) ProtoMessage()    {}
func (*Requirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{1}
}

func (m *Requirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requirement.Unmarshal(m, b)
}
func (m *Requirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requirement.Marshal(b, m, deterministic)
}
func (m *Requirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requirement.Merge(m, src)
}
func (m *Requirement) XXX_Size() int {
	return xxx_messageInfo_Requirement.Size(m)
}
func (m *Requirement) XXX_DiscardUnknown() {
	xxx_messageInfo_Requirement.DiscardUnknown(m)
}

var xxx_messageInfo_Requirement proto.InternalMessageInfo

func (m *Requirement) GetSpace() int32 {
	if m != nil {
		return m.Space
	}
	return 0
}

func (m *Requirement) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func init() {
	proto.RegisterType((*Vessel)(nil), "vessel.Vessel")
	proto.RegisterType((*Requirement)(nil), "vessel.Requirement")
	proto.RegisterType((*Response)(nil), "vessel.Response")
}

func init() { proto.RegisterFile("proto/vessel/vessel.proto", fileDescriptor_04ef66862bb50716) }

var fileDescriptor_04ef66862bb50716 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0x7e, 0x37, 0x6d, 0xd2, 0x64, 0x4a, 0xcb, 0xcb, 0xe8, 0x61, 0x2b, 0x0a, 0x21, 0x07, 0xc9,
	0xa9, 0x42, 0xbd, 0x78, 0xd5, 0x83, 0xd0, 0xeb, 0x0a, 0x7a, 0x11, 0xca, 0xb6, 0x19, 0x74, 0x21,
	0x5f, 0x66, 0x63, 0xda, 0xdf, 0xe2, 0xaf, 0x15, 0x66, 0x53, 0x23, 0xa2, 0xa7, 0x3c, 0x1f, 0x99,
	0xe1, 0x79, 0x66, 0x61, 0x51, 0x37, 0x55, 0x5b, 0x5d, 0x75, 0x64, 0x2d, 0xe5, 0xfd, 0x67, 0xc9,
	0x1a, 0x06, 0x8e, 0x25, 0x1f, 0x02, 0x82, 0x47, 0x86, 0x38, 0x07, 0xcf, 0x64, 0x52, 0xc4, 0x22,
	0x8d, 0x94, 0x67, 0x32, 0x3c, 0x05, 0xdf, 0xd6, 0x7a, 0x47, 0xd2, 0x8b, 0x45, 0xea, 0x2b, 0x47,
	0xf0, 0x02, 0xa0, 0xd0, 0x87, 0xcd, 0x9e, 0xcc, 0xcb, 0x6b, 0x2b, 0x47, 0x6c, 0x45, 0x85, 0x3e,
	0x3c, 0xb1, 0x80, 0x08, 0xe3, 0x52, 0x17, 0x24, 0xc7, 0xbc, 0x86, 0x31, 0x9e, 0x43, 0xa4, 0x3b,
	0x6d, 0x72, 0xbd, 0xcd, 0x49, 0xfa, 0xb1, 0x48, 0x43, 0x35, 0x08, 0xb8, 0x80, 0xb0, 0xda, 0x97,
	0xd4, 0x6c, 0x4c, 0x26, 0x03, 0x9e, 0x9a, 0x30, 0x5f, 0x67, 0xc9, 0x1d, 0x4c, 0x15, 0xbd, 0xbd,
	0x9b, 0x86, 0x0a, 0x2a, 0xdb, 0x21, 0x90, 0xf8, 0x3b, 0x90, 0xf7, 0x23, 0x50, 0xf2, 0x0c, 0xa1,
	0x22, 0x5b, 0x57, 0xa5, 0x25, 0xbc, 0x84, 0xbe, 0x36, 0x6f, 0x98, 0xae, 0xe6, 0xcb, 0xfe, 0x26,
	0xee, 0x02, 0xaa, 0x77, 0x31, 0x85, 0x89, 0x43, 0x56, 0x7a, 0xf1, 0xe8, 0x97, 0x1f, 0x8f, 0xf6,
	0x6a, 0x0d, 0x33, 0x27, 0x3d, 0x50, 0xd3, 0x99, 0x1d, 0xe1, 0x0d, 0xcc, 0xee, 0x4d, 0x99, 0xdd,
	0x7e, 0xd5, 0x3b, 0x39, 0x8e, 0x7e, 0x6b, 0x72, 0xf6, 0x7f, 0x10, 0x5d, 0xb4, 0xe4, 0xdf, 0x36,
	0xe0, 0x87, 0xb9, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x2e, 0x1b, 0xd8, 0xb5, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	FindAvailable(ctx context.Context, in *Requirement, opts ...client.CallOption) (*Response, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) FindAvailable(ctx context.Context, in *Requirement, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	FindAvailable(context.Context, *Requirement, *Response) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) FindAvailable(ctx context.Context, in *Requirement, out *Response) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}
